services:
  - type: web
    name: taskmanagement-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: QUARKUS_PROFILE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: RABBITMQ_HOST
        sync: false
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USERNAME
        sync: false
      - key: RABBITMQ_PASSWORD
        sync: false
      - key: KAFKA_HOST
        sync: false
      - key: KAFKA_PORT
        value: "9092"
      - key: EMAIL_ENABLED
        value: "false"
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: noreply@taskmanagement.com
