# Quarkus Application
project.artifactId=task-management-backend
project.version=1.0.0-SNAPSHOT

# Build
maven.compiler.source=21
maven.compiler.target=21
project.build.sourceEncoding=UTF-8
quarkus.native.container-build=true

# Database
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=none

# Messaging
mp.messaging.outgoing.task-events-out.connector=smallrye-rabbitmq
mp.messaging.incoming.task-created-email.connector=smallrye-rabbitmq

# Security
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
